const DATA={cats:{WIDE:"Широкоформатная печать",CANVAS:"Холсты",POLY:"Полиграфия",LETTERS:"Буквы и формы",PLOTTER:"Плоттерная резка",VOLUME:"Объёмные буквы"},products:[
{c:"BANNER",cat:"WIDE",n:"Баннер",t:"area",d:"Цена зависит от площади и вида баннерной ткани",v:[["Тонкий баннер менее 440 г",400],["Толстый баннер 440 г",400]],s:[["Проклей",60,"пог. м"],["Люверсы",30,"шт."]]},
{c:"PLENKA_PRINT",cat:"WIDE",n:"Плёнка с печатью",t:"area",d:"Матовая, глянцевая, прозрачная, перфорированная",v:[["Матовая",600],["Глянцевая",600],["Прозрачная",600],["Перфорированная",800]],s:[["Рез",50,"пог. м"]]},
{c:"HOLST",cat:"CANVAS",n:"Холст на подрамнике",t:"fixed",d:"Готовые размеры холстов",sizes:[[30,30,1750],[40,40,2000],[50,50,2350],[60,60,1750],[100,100,4350],[30,21,1650],[30,40,1900],[30,45,1950],[40,50,2200],[40,60,2300],[50,60,2450],[50,70,2650],[60,70,2850],[60,80,3000],[60,90,3200],[70,90,3450],[70,100,3600],[80,100,3850],[80,120,4300],[90,140,5000],[100,150,5650],[100,200,6900]]},
{c:"SRA3",cat:"POLY",n:"Печать SRA3",t:"sheet",d:"Печать на листах SRA3",v:[["Бумага 130 г · 4+0",100],["Бумага 130 г · 4+4",150],["Бумага 270 г · 4+0",100],["Бумага 270 г · 4+4",150],["Самоклеящаяся бумага",150],["Плёнка",300]]},
{c:"VISITKI",cat:"POLY",n:"Визитки",t:"business",d:"Фиксированные тиражи и стороны печати",v:[["120 шт · 4+0",550],["120 шт · 4+4",750],["1020 шт · 4+0 · 2–3 дня",5000],["1020 шт · 4+4 · 2–3 дня",7000],["1000 шт · 4+0 · 14–18 дней",2500],["1000 шт · 4+4 · 14–18 дней",2500]]},
{c:"BUKVA_MATERIAL",cat:"LETTERS",n:"Буквы из материалов",t:"area",d:"Материал по площади + резка контура",v:[["Акрил",5000],["Полистирол",4000],["ПВХ",3000],["ХДФ",1000],["ПЭТ",2000]],s:[["Резка по контуру",50,"пог. м"]]},
{c:"POLOTNO_FORMA",cat:"LETTERS",n:"Полотна и формы",t:"area",d:"Материал по площади + резка контура",v:[["Акрил",5000],["ПВХ",3000],["ХДФ",1000],["ДСП",700],["ПЭТ",2000]],s:[["Резка по контуру",50,"пог. м"]]},
{c:"PLENKA_PLOTTER",cat:"PLOTTER",n:"Плёнка на плоттере",t:"area",d:"Виниловая или металлизированная плёнка",v:[["Виниловая",2000],["Металлизированная",2300]]},
{c:"BYKVA_OBIEM",cat:"VOLUME",n:"Объёмные буквы",t:"area",d:"Цена зависит от площади",v:[["Стандарт",12000]]},
{c:"BYKVA_OBIEM_SVET",cat:"VOLUME",n:"Объёмные буквы с подсветкой",t:"area",d:"Цена зависит от площади",v:[["С подсветкой",25000]]},
{c:"SATIN_PAPER",cat:"WIDE",n:"Сатиновая бумага",t:"area",d:"Широкоформатная печать на сатиновой бумаге",v:[["Сатиновая бумага",1000]]}
]};const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let cur=null;const money=n=>new Intl.NumberFormat("ru-RU").format(Math.round(n))+" ₽";
function renderProducts(){$("#products").innerHTML=DATA.products.map((p,i)=>`<button class="product" data-i="${i}">◫<b>${p.n}</b><em>${DATA.cats[p.cat]}</em></button>`).join("");$$(".product").forEach(b=>b.onclick=()=>openProduct(+b.dataset.i))}
function openProduct(i){cur=DATA.products[i];$("#products").classList.add("hidden");$("#form").classList.remove("hidden");$("#category").textContent=DATA.cats[cur.cat];$("#productName").textContent=cur.n;$("#comment").textContent=cur.d||"";$("#variantWrap").classList.toggle("hidden",cur.t==="fixed");$("#fixedSizeWrap").classList.toggle("hidden",cur.t!=="fixed");$("#dimensions").classList.toggle("hidden",["fixed","sheet","business"].includes(cur.t));$("#q").parentElement.classList.toggle("hidden",cur.t==="business");if(cur.v)$("#variant").innerHTML=cur.v.map((v,i)=>`<option value="${i}">${v[0]}</option>`).join("");if(cur.sizes)$("#fixedSize").innerHTML=cur.sizes.map((s,i)=>`<option value="${i}">${s[0]}×${s[1]} см — ${money(s[2])}</option>`).join("");renderServices();calc()}
function renderServices(){const box=$("#services");box.innerHTML=(cur.s||[]).map((s,i)=>`<div class="service"><input type="checkbox" data-si="${i}"><span>${s[0]} · ${money(s[1])}/${s[2]}</span><input class="serviceQty" data-qi="${i}" type="number" min="0" step="1" value="0" placeholder="Количество"></div>`).join("");box.classList.toggle("hidden",!(cur.s||[]).length);box.querySelectorAll("input").forEach(x=>x.addEventListener("input",calc))}
function calc(){if(!cur)return;let base=0,q=Math.max(1,+$("#q").value||1),idx=+$("#variant").value||0;if(cur.t==="area"){base=(+$("#w").value||0)*(+$("#h").value||0)*(cur.v[idx]?.[1]||0)*q}else if(cur.t==="fixed"){base=(cur.sizes[+$("#fixedSize").value||0]?.[2]||0)*q}else if(cur.t==="sheet"){base=(cur.v[idx]?.[1]||0)*q}else if(cur.t==="business"){base=cur.v[idx]?.[1]||0}let extra=0;(cur.s||[]).forEach((s,i)=>{const ch=$(`[data-si="${i}"]`),qty=+$(`[data-qi="${i}"]`)?.value||0;if(ch?.checked)extra+=s[1]*qty});let design=$("#designCheck").checked?(+$("#designPrice").value||0):0;$("#basePrice").textContent=money(base);$("#serviceLine").classList.toggle("hidden",!extra);$("#servicePrice").textContent=money(extra);$("#designLine").classList.toggle("hidden",!design);$("#designOut").textContent=money(design);$("#total").textContent=money(base+extra+design);return{base,extra,design,total:base+extra+design}}
["w","h","q","variant","fixedSize","designPrice"].forEach(id=>$("#"+id).addEventListener("input",calc));$("#designCheck").onchange=()=>{$("#designPriceWrap").classList.toggle("hidden",!$("#designCheck").checked);calc()};$("#backProducts").onclick=()=>{$("#form").classList.add("hidden");$("#products").classList.remove("hidden")};
function getSaved(){try{return JSON.parse(localStorage.getItem("luxprint-calcs")||"[]")}catch{return[]}}function setSaved(x){localStorage.setItem("luxprint-calcs",JSON.stringify(x));renderSaved()}
$("#save").onclick=()=>{const c=calc(),arr=getSaved();arr.unshift({id:Date.now(),name:cur.n,total:c.total,date:new Date().toLocaleDateString("ru-RU")});setSaved(arr);$("#save").textContent="Сохранено ✓";setTimeout(()=>$("#save").textContent="Сохранить расчёт",1200)};
function renderSaved(){const a=getSaved();$("#savedCount").textContent=a.length;$("#savedList").innerHTML=a.length?a.map(x=>`<article class="savedCard"><div><h3>${x.name}</h3><p>${x.date}</p><strong>${money(x.total)}</strong></div><button data-del="${x.id}">Удалить</button></article>`).join(""):`<div class="empty">Пока нет сохранённых расчётов.</div>`;$$("[data-del]").forEach(b=>b.onclick=()=>setSaved(a.filter(x=>x.id!=b.dataset.del)))}
function tab(saved){$("#calculatorView").classList.toggle("hidden",saved);$("#savedView").classList.toggle("hidden",!saved);$("#calcTab").classList.toggle("active",!saved);$("#savedTab").classList.toggle("active",saved);if(saved)renderSaved()}$("#calcTab").onclick=()=>tab(false);$("#savedTab").onclick=()=>tab(true);$("#order").onclick=()=>alert("Следующим этапом подключим форму заявки менеджеру.");renderProducts();renderSaved();